///
/// @Generated by Mockolo
///



import CoreLocation
import Foundation
import RIBs
import ReactorKit
import RxRelay
import RxSwift
import UIKit
@testable import RIBsReactorKit


final class RootInteractableMock: RootInteractable {
    init() { }
    init(router: RootRouting? = nil, listener: RootListener? = nil, isActive: Bool = false, isActiveStream: Observable<Bool> = PublishSubject<Bool>()) {
        self.router = router
        self.listener = listener
        self.isActive = isActive
        self.isActiveStream = isActiveStream
    }


    private(set) var routerSetCallCount = 0
    var router: RootRouting? = nil { didSet { routerSetCallCount += 1 } }

    private(set) var listenerSetCallCount = 0
    var listener: RootListener? = nil { didSet { listenerSetCallCount += 1 } }
    public private(set) var isActiveSetCallCount = 0
    public var isActive: Bool = false { didSet { isActiveSetCallCount += 1 } }
    private var isActiveStreamSubjectKind = 0
    public private(set) var isActiveStreamSubjectSetCallCount = 0
    public var isActiveStreamSubject = PublishSubject<Bool>() { didSet { isActiveStreamSubjectSetCallCount += 1 } }
    public var isActiveStreamReplaySubject = ReplaySubject<Bool>.create(bufferSize: 1) { didSet { isActiveStreamSubjectSetCallCount += 1 } }
    public var isActiveStreamBehaviorSubject: BehaviorSubject<Bool>! { didSet { isActiveStreamSubjectSetCallCount += 1 } }
    public var _isActiveStream: Observable<Bool>! { didSet { isActiveStreamSubjectSetCallCount += 1 } }
    public var isActiveStream: Observable<Bool> {
        get {
            if isActiveStreamSubjectKind == 0 {
                return isActiveStreamSubject
            } else if isActiveStreamSubjectKind == 1 {
                return isActiveStreamBehaviorSubject
            } else if isActiveStreamSubjectKind == 2 {
                return isActiveStreamReplaySubject
            } else {
                return _isActiveStream
            }
        }
        set {
            if let val = newValue as? PublishSubject<Bool> {
                isActiveStreamSubject = val
                isActiveStreamSubjectKind = 0
            } else if let val = newValue as? BehaviorSubject<Bool> {
                isActiveStreamBehaviorSubject = val
                isActiveStreamSubjectKind = 1
            } else if let val = newValue as? ReplaySubject<Bool> {
                isActiveStreamReplaySubject = val
                isActiveStreamSubjectKind = 2
            } else {
                _isActiveStream = newValue
                isActiveStreamSubjectKind = 3
            }
        }
    }
    public private(set) var activateCallCount = 0
    public var activateHandler: (() -> ())?
    public func activate()  {
        activateCallCount += 1
        if let activateHandler = activateHandler {
            activateHandler()
        }
        
    }
    public private(set) var deactivateCallCount = 0
    public var deactivateHandler: (() -> ())?
    public func deactivate()  {
        deactivateCallCount += 1
        if let deactivateHandler = deactivateHandler {
            deactivateHandler()
        }
        
    }
}

final class RootRoutingMock: RootRouting {
    init() { }
    init(lifecycle: Observable<RouterLifecycle> = PublishSubject<RouterLifecycle>(), interactable: Interactable = InteractableMock(), children: [Routing] = [Routing]()) {
        self.lifecycle = lifecycle
        self.interactable = interactable
        self.children = children
    }


    private(set) var attachMainTabBarRIBCallCount = 0
    var attachMainTabBarRIBHandler: (() -> ())?
    func attachMainTabBarRIB()  {
        attachMainTabBarRIBCallCount += 1
        if let attachMainTabBarRIBHandler = attachMainTabBarRIBHandler {
            attachMainTabBarRIBHandler()
        }
        
    }

    private(set) var cleanupViewsCallCount = 0
    var cleanupViewsHandler: (() -> ())?
    func cleanupViews()  {
        cleanupViewsCallCount += 1
        if let cleanupViewsHandler = cleanupViewsHandler {
            cleanupViewsHandler()
        }
        
    }
    private var lifecycleSubjectKind = 0
    public private(set) var lifecycleSubjectSetCallCount = 0
    public var lifecycleSubject = PublishSubject<RouterLifecycle>() { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycleReplaySubject = ReplaySubject<RouterLifecycle>.create(bufferSize: 1) { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycleBehaviorSubject: BehaviorSubject<RouterLifecycle>! { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var _lifecycle: Observable<RouterLifecycle>! { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycle: Observable<RouterLifecycle> {
        get {
            if lifecycleSubjectKind == 0 {
                return lifecycleSubject
            } else if lifecycleSubjectKind == 1 {
                return lifecycleBehaviorSubject
            } else if lifecycleSubjectKind == 2 {
                return lifecycleReplaySubject
            } else {
                return _lifecycle
            }
        }
        set {
            if let val = newValue as? PublishSubject<RouterLifecycle> {
                lifecycleSubject = val
                lifecycleSubjectKind = 0
            } else if let val = newValue as? BehaviorSubject<RouterLifecycle> {
                lifecycleBehaviorSubject = val
                lifecycleSubjectKind = 1
            } else if let val = newValue as? ReplaySubject<RouterLifecycle> {
                lifecycleReplaySubject = val
                lifecycleSubjectKind = 2
            } else {
                _lifecycle = newValue
                lifecycleSubjectKind = 3
            }
        }
    }
    public private(set) var interactableSetCallCount = 0
    public var interactable: Interactable = InteractableMock() { didSet { interactableSetCallCount += 1 } }
    public private(set) var childrenSetCallCount = 0
    public var children: [Routing] = [Routing]() { didSet { childrenSetCallCount += 1 } }
    public private(set) var loadCallCount = 0
    public var loadHandler: (() -> ())?
    public func load()  {
        loadCallCount += 1
        if let loadHandler = loadHandler {
            loadHandler()
        }
        
    }
    public private(set) var attachChildCallCount = 0
    public var attachChildHandler: ((Routing) -> ())?
    public func attachChild(_ child: Routing)  {
        attachChildCallCount += 1
        if let attachChildHandler = attachChildHandler {
            attachChildHandler(child)
        }
        
    }
    public private(set) var detachChildCallCount = 0
    public var detachChildHandler: ((Routing) -> ())?
    public func detachChild(_ child: Routing)  {
        detachChildCallCount += 1
        if let detachChildHandler = detachChildHandler {
            detachChildHandler(child)
        }
        
    }
}

final class MainTabBarRoutingMock: MainTabBarRouting {
    init() { }
    init(lifecycle: Observable<RouterLifecycle> = PublishSubject<RouterLifecycle>(), viewControllable: ViewControllable = ViewControllableMock(), interactable: Interactable = InteractableMock(), children: [Routing] = [Routing]()) {
        self.lifecycle = lifecycle
        self.viewControllable = viewControllable
        self.interactable = interactable
        self.children = children
    }


    private(set) var attachTabsCallCount = 0
    var attachTabsHandler: (() -> ())?
    func attachTabs()  {
        attachTabsCallCount += 1
        if let attachTabsHandler = attachTabsHandler {
            attachTabsHandler()
        }
        
    }
    private var lifecycleSubjectKind = 0
    public private(set) var lifecycleSubjectSetCallCount = 0
    public var lifecycleSubject = PublishSubject<RouterLifecycle>() { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycleReplaySubject = ReplaySubject<RouterLifecycle>.create(bufferSize: 1) { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycleBehaviorSubject: BehaviorSubject<RouterLifecycle>! { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var _lifecycle: Observable<RouterLifecycle>! { didSet { lifecycleSubjectSetCallCount += 1 } }
    public var lifecycle: Observable<RouterLifecycle> {
        get {
            if lifecycleSubjectKind == 0 {
                return lifecycleSubject
            } else if lifecycleSubjectKind == 1 {
                return lifecycleBehaviorSubject
            } else if lifecycleSubjectKind == 2 {
                return lifecycleReplaySubject
            } else {
                return _lifecycle
            }
        }
        set {
            if let val = newValue as? PublishSubject<RouterLifecycle> {
                lifecycleSubject = val
                lifecycleSubjectKind = 0
            } else if let val = newValue as? BehaviorSubject<RouterLifecycle> {
                lifecycleBehaviorSubject = val
                lifecycleSubjectKind = 1
            } else if let val = newValue as? ReplaySubject<RouterLifecycle> {
                lifecycleReplaySubject = val
                lifecycleSubjectKind = 2
            } else {
                _lifecycle = newValue
                lifecycleSubjectKind = 3
            }
        }
    }
    public private(set) var viewControllableSetCallCount = 0
    public var viewControllable: ViewControllable = ViewControllableMock() { didSet { viewControllableSetCallCount += 1 } }
    public private(set) var interactableSetCallCount = 0
    public var interactable: Interactable = InteractableMock() { didSet { interactableSetCallCount += 1 } }
    public private(set) var childrenSetCallCount = 0
    public var children: [Routing] = [Routing]() { didSet { childrenSetCallCount += 1 } }
    public private(set) var loadCallCount = 0
    public var loadHandler: (() -> ())?
    public func load()  {
        loadCallCount += 1
        if let loadHandler = loadHandler {
            loadHandler()
        }
        
    }
    public private(set) var attachChildCallCount = 0
    public var attachChildHandler: ((Routing) -> ())?
    public func attachChild(_ child: Routing)  {
        attachChildCallCount += 1
        if let attachChildHandler = attachChildHandler {
            attachChildHandler(child)
        }
        
    }
    public private(set) var detachChildCallCount = 0
    public var detachChildHandler: ((Routing) -> ())?
    public func detachChild(_ child: Routing)  {
        detachChildCallCount += 1
        if let detachChildHandler = detachChildHandler {
            detachChildHandler(child)
        }
        
    }
}

final class RootListenerMock: RootListener {
    init() { }


}

final class RootViewControllableMock: RootViewControllable {
    init() { }
    init(uiviewController: UIViewController = UIViewController()) {
        self.uiviewController = uiviewController
    }

    public private(set) var uiviewControllerSetCallCount = 0
    public var uiviewController: UIViewController = UIViewController() { didSet { uiviewControllerSetCallCount += 1 } }
}

final class MainTabBarBuildableMock: MainTabBarBuildable {
    init() { }


    private(set) var buildCallCount = 0
    var buildHandler: ((MainTabBarBuildDependency) -> (MainTabBarRouting))?
    func build(with dynamicBuildDependency: MainTabBarBuildDependency) -> MainTabBarRouting {
        buildCallCount += 1
        if let buildHandler = buildHandler {
            return buildHandler(dynamicBuildDependency)
        }
        return MainTabBarRoutingMock()
    }
}

