# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'CI Test'
  lane :ci_test do
    run_tests(
      workspace: 'RIBsReactorKit.xcworkspace',
      scheme: 'RIBsReactorKit',
      device: 'iPhone 12 Pro',
      ensure_devices_found: true,
      force_quit_simulator: true,
      prelaunch_simulator: true,
      code_coverage: true,
      clean: true
    )
  end
end