disabled_rules: # 실행에서 제외할 룰 식별자들
  - trailing_whitespace
  - colon
  - opening_brace
opt_in_rules: # 일부 룰은 옵트 인 형태로 제공
  - empty_count
  - missing_docs
  - comments_space
  # 사용 가능한 모든 룰은 swiftlint rules 명령으로 확인 가능
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
  - RIBsReactorKit/Source
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Pods
  - Carthage
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
# 설정 가능한 룰은 이 설정 파일에서 커스터마이징 가능
# 경고나 에러 중 하나를 발생시키는 룰은 위반 수준을 설정 가능
colon: error
force_cast: warning # 암시적으로 지정
force_try:
  severity: warning # 명시적으로 지정
line_length: 100
function_parameter_count: 6
# 경고 및 에러 둘 다 존재하는 룰의 경우 값을 하나만 지정하면 암시적으로 경고 수준에 설정됨
# 값을 나열해서 암시적으로 양쪽 다 지정할 수 있음
type_body_length:
  - 300 # 경고
  - 400 # 에러
# 둘 다 명시적으로 지정할 수도 있음
file_length:
  warning: 1000
  error: 1200
# 네이밍 룰은 경고/에러에 min_length와 max_length를 각각 설정 가능
# 제외할 이름을 설정할 수 있음
type_name:
  min_length: 3 # 경고에만 적용됨
  max_length: # 경고와 에러 둘 다 적용
    warning: 70
    error: 80
  excluded: # 제외할 문자열 값 사용
   - iPhone
   - ID
identifier_name:
  min_length: # min_length에서
    error: 2 # 에러만 적용
  excluded: # 제외할 문자열 목록 사용
    - id
    - URL
reporter: "xcode" # 보고 유형 (xcode, json, csv, checkstyle, junit, html, emoji, markdown)