@startmindmap
<style>
mindmapDiagram {
  . * {
    BackGroundColor #FFF
    LineColor #192f60
    Shadowing 0.0
    RoundCorner 20
    LineThickness 2.0
  }
  .noView * {
    BackGroundColor #FFF
    LineColor #d20b52
    TextColor #d20b52
  }
}
</style>
* Root<<noView>>
** MainTabBar
*** UserCollection
**** ImagePrefetchWorker<<noView>>
**** UserInformation
***** UserLocation
*** UserList
**** ImagePrefetchWorker<<noView>>
**** UserInformation
***** UserLocation
@endmindmap